#!/bin/bash

# this is intended for use by GitHub Codespaces
# actual script at .config/yadm/bootstrap

sudo apt update && sudo apt install yadm
yadm clone https://github.com/jasonappah/dotfiles --bootstrap -b main
