tap "artginzburg/tap"
tap "dokku/repo"
tap "hackclub/tap"
tap "hacker1024/hacker1024"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "linuss1/taps"
tap "matt-gleich/taps"
tap "quackduck/tap"
tap "railwayapp/railway"
tap "smokris/getwindowid"
tap "superfly/tap"
brew "act"
brew "giflib"
brew "jpeg"
brew "libpng"
brew "webp"
brew "sqlite"
brew "python@3.10"
brew "asciinema"
brew "glib"
brew "bat"
brew "bit-git"
brew "bitwarden-cli"
brew "bpytop"
brew "caddy"
brew "pkg-config"
brew "cairo"
brew "checkstyle"
brew "chrome-cli"
brew "clang-format"
brew "cmake"
brew "cmatrix"
brew "cppcheck"
brew "curaengine"
brew "curl"
brew "deno"
brew "diff-so-fancy"
brew "docker-compose"
brew "doctl"
brew "dog"
brew "doxygen"
brew "duf"
brew "exa"
brew "exiftool"
brew "gobject-introspection"
brew "libass"
brew "ffmpeg"
brew "fish"
brew "pango"
brew "fontforge"
brew "fzf"
brew "gcc"
brew "gdk-pixbuf"
brew "genact"
brew "gh"
brew "git"
brew "glib-networking"
brew "gnupg"
brew "go"
brew "google-java-format"
brew "netpbm"
brew "librsvg"
brew "graphviz"
brew "gstreamer"
brew "gtk+3"
brew "handbrake"
brew "helm"
brew "htop"
brew "hugo"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "libnice"
brew "libpsl"
brew "libsoup"
brew "llvm"
brew "lolcat"
brew "lynx"
brew "macchina"
brew "macos-trash"
brew "mas"
brew "mdbook"
brew "micro"
brew "minikube"
brew "protobuf"
brew "mitmproxy"
brew "mosh"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "nnn"
brew "nvm"
brew "pinentry-mac"
brew "poetry"
brew "pyenv"
brew "python@3.8"
brew "qemu"
brew "rbenv"
brew "rustup-init"
brew "scrcpy"
brew "sl"
brew "ssh-copy-id"
brew "tig"
brew "tmux"
brew "tty-clock"
brew "vala"
brew "w3m"
brew "wget"
brew "wifi-password"
brew "yadm"
brew "yamllint"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "artginzburg/tap/sudo-touchid"
brew "hackclub/tap/haas"
brew "hacker1024/hacker1024/coretemp"
brew "heroku/brew/heroku"
brew "jakehilborn/jakehilborn/displayplacer"
brew "matt-gleich/taps/fgh"
brew "quackduck/tap/tii"
brew "railwayapp/railway/railway"
brew "smokris/getwindowid/getwindowid"
brew "superfly/tap/flyctl"
cask "adobe-creative-cloud"
cask "android-platform-tools"
cask "balenaetcher"
cask "cron"
cask "discord"
cask "dteoh-devdocs"
cask "fig"
cask "firefox"
cask "flutter"
cask "google-cloud-sdk"
cask "google-drive"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keka"
cask "krisp"
cask "launchcontrol"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "notion"
cask "obs"
cask "onyx"
cask "sf-symbols"
cask "teamviewer"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "wireshark"
cask "xquartz"
cask "zoom"
mas "1Focus", id: 969210610
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Boop", id: 1518425043
mas "Buddymove", id: 1491012222
mas "Contrast", id: 1254981365
mas "Craft", id: 1487937127
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "Flow", id: 1423210932
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "Hidden Bar", id: 1452453066
mas "Horo", id: 1437226581
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pandan", id: 1569600264
mas "QR Capture", id: 1369524274
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Startup Disk Full Fixer", id: 1346655838
mas "Tailscale", id: 1475387142
mas "TeraTime", id: 1348795218
mas "Termius", id: 1176074088
mas "TickTick", id: 966085870
mas "Trello", id: 1278508951
mas "WireGuard", id: 1451685025
