#!/bin/bash

# get homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing Homebrew..."
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# really spending more time automating this than it would actually take me to do manually lol
# m1 mac moment :/
if [[ -e /opt/homebrew/bin/brew ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.special.zsh
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# install most of my important tools
if command -v brew >/dev/null 2>&1; then
    brew bundle --no-lock
	nvm install --lts
fi

if command -v corepack >/dev/null 2>&1; then
    corepack enable
fi

if command -v yarn >/dev/null 2>&1; then
    cd $(yarn global dir) && yarn
fi

# install oh-my-zsh + other extensions not managed by brew 
KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

