#!/bin/bash

if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew..."
  curl -fsSL "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
fi

brew bundle

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
