[v1]
"cargo-cache 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-edit 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-make 0.35.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-make",
    "makers",
]
"difftastic 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["difft"]
"dura 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dura"]
